name: sscaleg
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  #utilizado para gerar pdf
  pdf: ^3.10.1
  #utilizado para salvar
  # pdf no celular
  path_provider: ^2.0.14
  open_file: ^3.2.1
  # utilizado para salvar
  # pdf na web
  universal_html: ^2.2.1
  # necessario para notificacao elegante
  elegant_notification: ^2.2.2
  # necessario para gravar chaves valores
  shared_preferences: ^2.5.3
  # necessario para rodar firebase
  firebase_database: ^11.1.0
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.8
  #para carregar Imagem
  image_picker: ^1.1.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/imagens/
