// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMgXbES84pJ8ew4Z9Yeq08k01sGFa0UI',
    appId: '1:259654711735:web:8ed917d3b5bd06983a9032',
    messagingSenderId: '259654711735',
    projectId: 'sscaleg',
    authDomain: 'sscaleg.firebaseapp.com',
    storageBucket: 'sscaleg.firebasestorage.app',
    measurementId: 'G-JPY5T76C66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd594Xl9bHpEZNR0YCAob_HdLiwszW38s',
    appId: '1:259654711735:android:cffcd916bc4046b43a9032',
    messagingSenderId: '259654711735',
    projectId: 'sscaleg',
    storageBucket: 'sscaleg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvdOkCelE_d6OLaex3oL8hTkEMQ9plG0',
    appId: '1:259654711735:ios:571d33afaaa7bffb3a9032',
    messagingSenderId: '259654711735',
    projectId: 'sscaleg',
    storageBucket: 'sscaleg.firebasestorage.app',
    iosBundleId: 'com.example.sscaleg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvdOkCelE_d6OLaex3oL8hTkEMQ9plG0',
    appId: '1:259654711735:ios:571d33afaaa7bffb3a9032',
    messagingSenderId: '259654711735',
    projectId: 'sscaleg',
    storageBucket: 'sscaleg.firebasestorage.app',
    iosBundleId: 'com.example.sscaleg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpMgXbES84pJ8ew4Z9Yeq08k01sGFa0UI',
    appId: '1:259654711735:web:e499ee56bec7265b3a9032',
    messagingSenderId: '259654711735',
    projectId: 'sscaleg',
    authDomain: 'sscaleg.firebaseapp.com',
    storageBucket: 'sscaleg.firebasestorage.app',
    measurementId: 'G-K6FCY4L5V0',
  );
}
